version: "3"

services:
  app:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    ports:
      - 8055:80
    environment:
      - TZ='Europe/Oslo'
    volumes:
      - ./data:/app/data
