---
version: "3"
services:
  coredns:
    container_name: coredns
    image: "coredns/coredns:1.10.1"
    restart: always
    volumes:
    - "./coredns:/etc/coredns"
    command: "-conf /etc/coredns/corefile"
    ports:
    - "53:53/udp"