---
version: "2.1"
services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - ./conf:/config
    ports:
      - 8088:8088
    restart: unless-stopped
    
# https://github.com/bakito/adguardhome-sync/